# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graph-Drawing
version:      0.0901
version_from: lib/Graph/Drawing.pm
installdirs:  site
requires:
    Carp:                          0
    GD:                            0
    Graph::Weighted:               0.10
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
